libs:
	../makeobj stdio/print stdio/input stdio/i_print stdio/i_input stdio/err_print stdio.jo
	../makeobj stdlib/sqrt stdlib/sqr stdlib/sin stdlib/cos stdlib/int stdlib/float stdlib.jo # stdlib/tg stdlib/ctg stdlib/abs stdlib.jo
